apiVersion: v1
kind: Service
metadata:
  name: nginx-int
  namespace: internal
  labels:
    app: nginx-int
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx-int
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-int
  namespace: internal
  labels:
    app: nginx-int
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-int
  template:
    metadata:
      labels:
        app: nginx-int
    spec:
      containers:
      - name: nginx-int
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway-int
  namespace: internal
spec:
  # selector:
  #   istio: istio-ingressgateway-int
  servers:
  - port:
      number: 80
      name: http-test
      protocol: HTTP
    hosts:
    - test.sggovt-int.demoaxway.int
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-test
      protocol: HTTPS
    hosts:
    - test.sggovt-int.demoaxway.int
    tls:
      #mode: PASSTHROUGH
      mode: SIMPLE
      # credentialName: ingress-test-int-cert # This should match the Certificate secretName
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-1
  namespace: internal
spec:
  hosts:
  - "test.sggovt-int.demoaxway.int"
  # tls:
  # - match:
  #   - port: 443
  #     sniHosts:
  #     - nginx-cert-int.com
  gateways:
  - istio-ingressgateway-int
  http:
  - route:
    - destination:
        host: nginx-int
        port:
          number: 80