apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: external-gw
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway-ext
        enabled: true
        namespace: external
        label:
          istio: istio-ingressgateway-ext
        # Must be set for a private ELB only !
        # serviceAnnotations:
        #   "sservice.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
    egressGateways:
      - name: istio-egressgateway-ext
        enabled: true
        namespace: external
        label:
          istio: istio-egressgateway-ext