{{- if .Values.apitraffic.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "apitraffic.name" . }}
  labels: {{- include "apitraffic.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apitraffic.name }}
  minReplicas: {{ .Values.apitraffic.replicas }}
  maxReplicas: {{ .Values.apitraffic.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ default 70 .Values.apitraffic.autoscaling.averageUtilization }}
{{- end }}