apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: petstore
  namespace: test
spec:
  hosts:
  - petstore.swagger.io
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
