apiVersion: v1
kind: PersistentVolume
metadata:
  name: apim-ext-events-pv
  namespace: external
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <Must be changed>